### ISSUE TITLE
Extract method from exception

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#12]
You should add `${exception:format=Method}`:

https://github.com/elmahio/elmah.io.nlog/blob/4178e5af23adf91f400fb44d8f688bbda3c4f1b9/src/Elmah.Io.NLog/ElmahIoTarget.cs#L195

Btw. what is "type" used for (Is it like `${exception:format=type}`) ? 

https://github.com/elmahio/elmah.io.nlog/blob/4178e5af23adf91f400fb44d8f688bbda3c4f1b9/src/Elmah.Io.NLog/ElmahIoTarget.cs#L203

**Comment by ThomasArdal** [comment]
Any documentation for `${exception:format=Method}`? I cannot figure out what that is doing. Is it to fetch a `Method` property on the exception or something? So, in case it's a `HttpException` or similar, we would try to get the method?

The `type` field is intended for the exception full name, yes: https://github.com/elmahio/elmah.io.nlog/blob/4178e5af23adf91f400fb44d8f688bbda3c4f1b9/src/Elmah.Io.NLog/ElmahIoTarget.cs#L331

**Comment by snakefoot** [comment]
`${exception:format=Method}` comes from the [Exception TargetSite](https://docs.microsoft.com/en-us/dotnet/api/system.exception.targetsite):

https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer

**Comment by ThomasArdal** [comment]
Ah ok. Then I don't believe it would be the right value to put in the `method` field. In elmah.io terms, this is the HTTP method causing a log message.

**Comment by snakefoot** [comment]
With the fallback in `private string Type(LogEventInfo logEvent)`, then everything should be good.

**Comment by ThomasArdal** [comment]
Appreciate you looking through this 🙏
