### ISSUE TITLE
Change to NLog 4.5-rc02 and NetStandard1.5

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#3]
NLog 4.5 is going to be the next official release.

- Change dependency from NLog 5.0-beta11 to NLog 4.5-rc02.
- Change targetframeworks from `netStandard1.6` to `netStandard1.5`

**Comment by ThomasArdal** [comment]
@snakefoot Any input? https://github.com/elmahio/elmah.io.nlog/pull/5

**Comment by snakefoot** [comment]
Resolved with #5
