### ISSUE TITLE
ElmahIoTarget with less allocation

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#4]
- No need to allocate MachineNameLayoutRenderer for every logevent
- No need to allocate IdentityLayoutRenderer for every logevent
- No need to parse Guid for every logevent (Implement string-property to have Guid as backing-field)

**Comment by ThomasArdal** [comment]
@snakefoot Any input? https://github.com/elmahio/elmah.io.nlog/pull/5

**Comment by snakefoot** [comment]
Resolved with #5
