### ISSUE TITLE
Skip allocation of Item-List for every LogEvent

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#6]
Change this line:

`Data = PropertiesToData(logEvent.Properties),`

Into this line:

`Data = PropertiesToData(logEvent),`

And modify PropertiesToData like this:

        public static readonly Item[] EmptyArray = new Item[0];

        private IList<Item> PropertiesToData(LogEventInfo logEvent)
        {
            if (!logEvent.HasProperties)
                return EmptyArray;   // Replace with Array.Empty with net46

            var properties = logEvent.Properties;
            var items = new List<Item>(properties.Count);
            foreach (var obj in properties)
            {
                if (obj.Value != null)
                {
                    items.Add(new Item { Key = obj.Key.ToString(), Value = obj.Value.ToString() });
                }
            }
            return items;
        }

**Comment by ThomasArdal** [comment]
I'm not sure about the benefit of this change? So you want to return the same instance of the Item array, every time the log event doesn't have properties, rather than creating a new list every time?

**Comment by snakefoot** [comment]
An empty array should work just as good as an empty list. Alternatively one could just return null.


Sent from my Samsung device


-------- Original message --------

**Comment by ThomasArdal** [comment]
Returning null would be a better option I think. I'll check if the elmah.io client supports null (if it doesn't, it should) and make the change. Thanks! :smile:

**Comment by ThomasArdal** [comment]
Fixed in https://www.nuget.org/packages/elmah.io.nlog/3.1.39-pre
