### ISSUE TITLE
Change NetStandard1.5 to NetStandard1.4

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#7]
This will allow UWP10 application to work aswell:

https://github.com/elmahio/elmah.io.nlog/blob/b5b017e78d5ff2e7a79d738c4f13deb7d1e45c96/src/Elmah.Io.NLog/Elmah.Io.NLog.csproj#L6

**Comment by ThomasArdal** [comment]
Ah yeah, you are absolutely right. There's no reason not to support 1.4 really :smile: Thanks!

**Comment by ThomasArdal** [comment]
https://www.nuget.org/packages/elmah.io.nlog/3.1.41
