### ISSUE TITLE
Optimize parsing of NLog Properties and LogLevel

### ISSUE THREAD

**Issue by snakefoot** [elmahio/elmah.io.nlog#8]
Instead of parsing properties multiple times. Then it could be done once (without allocating extra strings):

```c#
        private List<Item> PropertiesToData(LogEventInfo logEvent,
                                            ref string application,
                                            ref string source,
                                            ref string hostname,
                                            ref string user,
                                            ref string method,
                                            ref string version,
                                            ref string url,
                                            ref string type,
                                            ref string statuscode)
        {
            if (!logEvent.HasProperties) return null;

            var items = new List<Item>(logEvent.Properties.Count);
            foreach (var obj in logEvent.Properties)
            {
                if (obj.Value != null)
                {
                    var propertyName = obj.Key.ToString();
                    var propertyValue = obj.Value.ToString();
                    if (string.Equals("application", propertyName, StringComparison.OrdinalIgnoreCase))
                           application = propertyValue;
                    else if (string.Equals("source", propertyName, StringComparison.OrdinalIgnoreCase))
                           source = propertyValue;
                    else if (string.Equals("hostname", propertyName, StringComparison.OrdinalIgnoreCase))
                           hostname = propertyValue;
                    else if (string.Equals("user", propertyName, StringComparison.OrdinalIgnoreCase))
                           user = propertyValue;
                    else if (string.Equals("method", propertyName, StringComparison.OrdinalIgnoreCase))
                           method = propertyValue;
                    else if (string.Equals("version", propertyName, StringComparison.OrdinalIgnoreCase))
                           version = propertyValue;
                    else if (string.Equals("url", propertyName, StringComparison.OrdinalIgnoreCase))
                           version = propertyValue;
                    else if (string.Equals("type", propertyName, StringComparison.OrdinalIgnoreCase))
                           type = propertyValue;
                    else if (string.Equals("statuscode", propertyName, StringComparison.OrdinalIgnoreCase))
                           statuscode = propertyValue;
                    items.Add(new Item { Key = propertyName, Value = propertyValue });
                }
            }
            return items;
       }
```

It could be really neat if CreateMessage-object accepted `ICollection<Item>` instead of `IList<Item>`. Then you could just convert `LogEventInfo.Properties` into `Dictionary<string,Item>` with `StringComparer.OrdinalIgnoreCase` as comparer. Then you could return `Dictionary.Values` as items-collection.

You should also fix `LevelToSeverity` so it doesn't allocate every time:

```c#
        private string LevelToSeverity(LogLevel level)
        {
            if (level == LogLevel.Debug) return nameof(Severity.Debug);
            if (level == LogLevel.Error) return nameof(Severity.Error);
            if (level == LogLevel.Fatal) return nameof(Severity.Fatal);
            if (level == LogLevel.Trace) return nameof(Severity.Verbose);
            if (level == LogLevel.Warn) return nameof(Severity.Warning);
            return nameof(Severity.Information);
        }
```

**Comment by ThomasArdal** [comment]
Those are some really interesting suggestions actually. I think that I may want to move the first part to a CreateMessage-method or something like that, to avoid the ref parameters. Thanks as always dude!

**Comment by ThomasArdal** [comment]
I've implemented your suggestion to `LevelToSeverity`. I have also switched from calling `ToString().ToLower()` to using `StringComparison.OrdinalIgnoreCase` which is a much cleaner way of writing the code. I will wait with the multiple iterations of `Properties` for now. I don't really like to look at code with `ref` parameters, but will think about how to reduce the number of times we need to iterate through all properties.

**Comment by ThomasArdal** [comment]
![you rock](https://user-images.githubusercontent.com/563206/48021032-cd61f500-e137-11e8-90ee-f1832b9330c6.gif)

**Comment by snakefoot** [comment]
Instead of doing this:

`if (logEvent.Properties == null || !logEvent.Properties.Any()) return null;`

Then I really recommend this:

`if (!logEvent.HasProperties) return null;`

- private List<Item> PropertiesToData(LogEventInfo logEvent)
- internal static int? Integer(this LogEventInfo logEvent, string name)
- internal static string String(this LogEventInfo logEvent, string name)

Also strange that your two extensions methods performs two sequential iterations. One to check, and one to extract. Also strange that they are identical except the one is doing int.TryParse. Why not let one call the other?

**Comment by ThomasArdal** [comment]
Awesome. Hadn't even noticed `HasProperties`. Fixed!

**Comment by ThomasArdal** [comment]
Totally forgot to comment on your suggestion about replacing `IList<Item>` with `ICollection<Item>`. I see how this would be beneficial, but `CreateMessage` is auto-generated code. I might be able to achieve it by changing the swagger JSON on the API, but want to keep this as stable as possible :smile:

**Comment by snakefoot** [comment]
@ThomasArdal Any reason why you don't implement all these as individual NLog Layout property-members on the Target:

- application,
- source,
- hostname - Ex: ${event-properties:hostname:whenEmpty=${machinename}}
- user,
- method,
- version,
- url,
- type,
- statuscode

Maybe a new option could be added to the NLog `${event-properties}` to be case-insensitive on lookup. Or maybe just have multiple lookup values. Ex. "hostname" + "Hostname" + "HostName".

**Comment by ThomasArdal** [comment]
When looking at this: https://github.com/NLog/NLog/issues/2995 isn't that exactly what you are proposing?

**Comment by snakefoot** [comment]
> When looking at this: NLog/NLog#2995 isn't that exactly what you are proposing?

Not sure I understand. By using Layout-properties as I'm suggesting here in this issue, then you get the ValueFormatter automatically.

**Comment by ThomasArdal** [comment]
Would it be too much trouble showing the code for a single property then? Not sure I understand :smile:

**Comment by snakefoot** [comment]
Something like this. I have not tested the code:
```c#
public class ElmahIoTarget : TargetWithLayout
{
        public Layout Hostname { get; set; } = "${event-properties:hostname:whenEmpty=${machinename}}";

       protected override void Write(LogEventInfo logEvent)
       {
             string hostName = RenderLogEvent(Hostname, logEvent);
       }
}
```

**Comment by snakefoot** [comment]
Btw. you should also consider to activate OptimizeBufferReuse (Below code change will also protect you from any future changes to the NLog default-Layout).

```c#
        private readonly string DefaultLayout;
        private bool _usingDefaultLayout;

        public ElmahIoTarget()
        {
             OptimizeBufferReuse = true;
             DefaultLayout = Layout?.ToString();
        }

        public ElmahIoTarget(IElmahioAPI client)
               :this()
        {
             _client = client;
        }

        protected override void InitializeTarget()
        {
             _usingDefaultLayout = Layout == null || Layout.ToString() == DefaultLayout;
        }

        protected override void Write(LogEventInfo logEvent)
        {
              var title = _usingDefaultLayout ? logEvent.FormattedMessage : RenderLogEvent(Layout, logEvent);
        }
```

**Comment by ThomasArdal** [comment]
Something like this: https://github.com/elmahio/elmah.io.nlog/blob/master/src/Elmah.Io.NLog/ElmahIoTarget.cs?

**Comment by snakefoot** [comment]
> @ThomasArdal Something like this...

Yes just like that. Maybe change to these gnarly expression to help against case-sensitive:

```
        public Layout HostnameLayout { get; set; } = "${event-properties:hostname:whenEmpty=${event-properties:Hostname:whenEmpty=${event-properties:HostName:whenEmpty=${machinename}}}}";

        public Layout SourceLayout { get; set; } = "${event-properties:source:whenEmpty=${event-properties:Source:whenEmpty=${logger}}}";

        public Layout ApplicationLayout { get; set; } = "${event-properties:application:whenEmpty=${event-properties:Application}}";

#if NET45
        public Layout UserLayout { get; set; } = "${event-properties:user:whenEmpty=${event-properties:User:whenEmpty=${identity:authType=false:isAuthenticated=false}}}";
#else
        public Layout UserLayout { get; set; } = "${event-properties:user:whenEmpty=${event-properties:User}}";
#endif

        public Layout MethodLayout { get; set; } = "${event-properties:method:whenEmpty=${event-properties:Method}}";

        public Layout VersionLayout { get; set; } = "${event-properties:version:whenEmpty=${event-properties:Version}}";

        public Layout UrlLayout { get; set; } = "${event-properties:url:whenEmpty=${event-properties:Url:whenEmpty=${event-properties:URL}}}";

        public Layout TypeLayout { get; set; } = "${event-properties:type:whenEmpty=${event-properties:Type}}";

        public Layout StatusCodeLayout { get; set; } = "${event-properties:statuscode:whenEmpty=${event-properties:Statuscode:whenEmpty=${event-properties:StatusCode}}}";
```

Remember to fix these also to use `RenderLogEvent`:

```
Source = Source(logEvent),
Application = ApplicationName(logEvent),
```

And maybe change this line:

`_usingDefaultLayout = Layout?.ToString() == DefaultLayout;`

To this line:

`_usingDefaultLayout = Layout == null || Layout.ToString() == DefaultLayout;`

**Comment by ThomasArdal** [comment]
Good suggestions. Source, Application and StatusCode do call RenderLogEvent. But in case that doesn't return a value, the methods picks some other values that I couldn't spot how to express as a layout renderer.

**Comment by snakefoot** [comment]
@ThomasArdal Have updated my suggestion so `SourceLayout` has fallback to `${logger}`

Cannot see any logic is happening for `ApplicationName`. Maybe my eyes have become old.

**Comment by ThomasArdal** [comment]
👍 on ${logger}.

ApplicationName returns the value of the Application property if nothing is found in properties.

**Comment by snakefoot** [comment]
@ThomasArdal Still recommend that you only allocate the StringBuilder for IEnumerable-objects. But if you really like the ValueFormatter, then you can do this:

```c#
        private List<Item> PropertiesToData(LogEventInfo logEvent)
        {
            if (!logEvent.HasProperties) return null;

            var items = new List<Item>();
            StringBuilder sb = null;
            var valueFormatter = ConfigurationItemFactory.Default.ValueFormatter;
            foreach (var obj in logEvent.Properties)
            {
                if (obj.Value != null)
                {
                     string text;
                     if (obj.Value is string)
                     {
                          text = (string)obj.Value;
                     }
                     else
                     {
                         sb = sb ?? new StringBuilder();
                         sb.Length = 0;  // Reuse StringBuilder
                         valueFormatter.FormatValue(obj.Value, null, CaptureType.Normal, null, sb);
                         text = sb.ToString();
                    }
                    items.Add(new Item { Key = obj.Key.ToString(), Value = text });
                }
            }
            return items;
      }
```

**Comment by ThomasArdal** [comment]
Looks nice! Making the last changes now. This is going to be great :smile:

**Comment by snakefoot** [comment]
About having both `Application`-property and `ApplicationLayout`-property, then should consider doing this:

```c#
public string Application { get => (ApplicationLayout as SimpleLayout)?.Text; set => ApplicationLayout = value; }

public Layout ApplicationLayout { get; set; } = "${event-properties:application:whenEmpty=${event-properties:Application}}";
```

**Comment by ThomasArdal** [comment]
Oh yeah. And then always `RenderLogEvent(ApplicationLayout, logEvent)`, right?

**Comment by snakefoot** [comment]
> Oh yeah. And then always RenderLogEvent(ApplicationLayout, logEvent), right?

Yes.
